// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import DashboardDemandesController from "./dashboard_demandes_controller"
application.register("dashboard-demandes", DashboardDemandesController)

import FlatpickerController from "./flatpicker_controller"
application.register("flatpicker", FlatpickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import StarReviewController from "./star_review_controller"
application.register("star-review", StarReviewController)
